#!/bin/sh
#
# Git pre-commit hooks.

echo "Running pre-commit hooks"

# retrieving current working directory
CWD=$(pwd)

# go to main project dir
cd $(git rev-parse --show-toplevel)

# run tests
mvn clean test

if [ $? -ne 0 ]; then
  "Error while testing the code"
  # go back to current working dir
  cd "$CWD" || exit 1
  exit 1
fi

# go back to current working dir
cd "$CWD" || exit 1
