runtime: java11

# https://cloud.google.com/appengine/docs/standard#instance_classes
instance_class: F2

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301